[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "rotarypendulum-mujoco"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["mujoco==3.14.0", "torch", "numpy", "tensordict==0.12.2", "rsl-rl-lib==5.0.1"]

[tool.setuptools.packages.find]
where = ["source/rotarypendulum"]

[tool.setuptools.package-data]
"rotarypendulum.rotarypendulumsimtoreal" = ["models/*.pth", "mjcf/*.xml"]
